services:
  dev_api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
    volumes:
      - ./src:/app/src
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    user: $DB_USERNAME
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PORT=$DB_PORT
      - POSTGRES_PASSWORD=$DB_PASSWORD
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
volumes:
  db-data:


